### ISSUE TITLE
About edit mode selection

### ISSUE THREAD

**Issue by rurires** [WistfulHopes/GBFRBlenderTools#12]
007e03467448c380b227aee545c38b3be17017ee
@AlphaSatanOmega 
Just a minor thing, but I have also encountered it before so I want to share this:

Blender use temporary data "bmesh" for edit mode, here is the document about accessing them:
https://docs.blender.org/api/current/bmesh.html#bmesh.from_edit_mesh

I use it like this:
```
import bpy
import bmesh

# After selecting a mesh object and enter edit mode
currentMesh = bpy.context.active_object.data
currentBMesh = bmesh.from_edit_mesh(currentMesh)

for edge in currentBMesh.edges:
    # do something here, such as:
    edge.select = True

# Refresh the view so user can see the changes,
# may not necessary for an operator.
bmesh.update_edit_mesh(
    currentMesh,
    loop_triangles=True,
    destructive=True
)
```
-----
Thank you for your great work!

**Comment by AlphaSatanOmega** [comment]
I may look into it more in the future, but I previously had some trouble understanding how to properly use bmesh.
This is my first time scripting in blender, so I'm still figuring things out.

As of now I see little reason to use it in favor of the bpy operators since most of the operations aren't too intensive, and the goals of the addon are simple enough to be done using bpy operators.
